{% set python_min = '3.12' %}
{% set name = "robotframework-appiumlibrary" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robotframework-appiumlibrary-{{ version }}.tar.gz
  sha256: 7171a81705bbfa0091c1cf6518277681752386c860efc6dd98c85d74970ad2a6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
    - setuptools
  run:
    - appium-python-client >=0.28
    - decorator >=3.3.2
    - docutils >=0.8.1
    - kitchen >=1.2.4
    - python >={{ python_min }}
    - robotframework >=2.6.0
    - selenium >=2.47.1
    - six >=1.10.0

test:
  imports:
    - AppiumLibrary
    - AppiumLibrary.keywords
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/serhatbolsu/robotframework-appiumlibrary
  summary: Robot Framework Mobile app testing library for Appium Client Android & iOS & Web
  license: Apache-2.0
  license_file: LICENSE.txt
extra:
  recipe-maintainers:
    - saibhargav1508
